# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QBRsIpl/jGf3kF5eVt55F0n9UcrjSw7RyvOSuzdoztXClU7h0E2hkdMHsUCKTWXL+cz5doUMdVykjq7e43mw1vNO/4EErK8WbAqQHh3xRMfx5A1XDPc5om+EsBv00oznzHr9SD85zpGhrRwVwReU2HuAYrF6Ww5cIRXkSjZGzqzuQd55aS6ItVyiYpLSZ4P6BSrGkA/tuYBexYvEswRcUPieC5kzklUzwml8zQ0mwLLMKZSjx2dwP2WkQzRuX5PQbsPZ3rJnMKp2FDk8ytNEWOUugoGMhNa9c2tZkLYahWs3Ev0PN4SqkfKO42oJkrX3dVjUQAZt/cVLQlLWEQNTGF+wPaJp2/WtbP9ibSrcE0UYjSh0QwDJz2UKB5lSTAi+n5nAf2/2QkQ0amTY2Pqnn8i4Zb3GH+OKuOOQtxuMWaNmr0TkMqurupNw/h6qHo1vyhJg7nuhD9cA7ZAwZZxAqYPpUVLYJbpDRKfYUR4Ye52o3XvimLcwslZokfnqP9+7BUfnSRzvNT06dhh1Gtv6YqJQsTIjPcN8Io/ji3ZdZ2Ohx8uGWZYnwYsTi2P8dQlYhDuInyoQfIWNKLsk7/X1HGcvFkb3HeWaPuWy4DAKR4C0lEemFkgZzQVjJ/KBwVyhkGChYZO9LMQyS7ToeIxkEHLeX1GsXzqYroNivKP1DAo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
