# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "v4J7DOE1mchNbseGbirjzm9R9Qdo5CQp5G+vqx+qx6G+mGgSVzFvw9c6BNwmGs66XWFu2fayIp+wyeaxunBMzBXbL1oyJwe1qOlT/v33NXKAe2f59k70XzAQ0ui5b4Ohv8c3jnraYpKLW8SnvYKwZtJ7Nbq0RP/ZUl5v4WXbtMs2xT+YEeI4aoM/vUcbzW8js9jGyeWuCv9RJ9suRc3hRJCIXRZj5UuVTEvyLHgs3xaTSUDKtBODNQJV5jHXP/B1b2EqCk3BDeeFkq62YgUDTqnooAluLDunNtYVI+fPPgY4NTOjavDB7wFlV38GpNUceW0UC19tsiXK6+zQYNMEHntGjDfE+p5u770+nc3EkYuIhwNgwjFizDIwyAW0pTb0ka6+TT9VtSw6dZdB6FIE1pk0UG4LQASmwSS8JTFwLDqH8QbEolYsFxfJGzrQyQiicNtA4044lsp7RJxtStctia9KQGtIuBLz6aYKgKQosJO/osA2IV6a7LN8Ma1WszXhgjm91zMP6NVhzZz3S+LjTq8omQa5RmOwBWOhtu6Qn8ktW2uRLRrYE4PftHDBueJwlQ2YoqlTU/Nx7UhSdVSy5Q0o4D+mtnKn0IcWnaCkQURh6jU62Ui+5v6VO64fhP0hX22y2wZz60TOkuOdBHjn7aQrwPQJ87/t8l7w49hm8eg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
