travis:
  secure:
    BINSTAR_TOKEN: CRV4jkm1+kAwGMlwykSVvziSUIOKCN+PcQeVx6oS1YFtrziafqZYe99El5qIv8BO2MxqblV5v0tIdDYUMduZunDlEotPQL+qFCloPDToJ30djj7o4nFTI9GlmihpDXL0kLbOcEG3RlroZ8EEAUDpHitOCq1XCy18keazOPN0fdlJOV7J4RBD4NpID6CeAbgysbPnUtG7qZVXUKcEvAj4fDcabeIxZeoVkR/KygEhPToAbbZwud07cIAhTt3ki6m/itEwNhxoj9nUlb/hSIpqMS1PPrV1+svgGX9cMGwXlN3LFYnabZ7ozH1IniZEq7tF1eAne22ICtJ/jcwo3JN9uUZyfGSWSa96LZTZuzDVHOzTU11veqnKOkATDsLP8eFeuAX5zZe+wL1V4KI84MtOVcNbY2VB55sGAeD5YC75qJUogNroCUe2bN8ucQmmsVxU3PnkA7tb3EokRxzb6zOp0E1RIT6JxL0a5QncLO0fe1olf2t11ZSO501fx3ZOImIUSCLVm9hDewE6bqjBfr/q6yrUAk6Cjfs7cRxIu/J6rO/iyhCPQbyVkJ6sCr7RH9gcZvs42BEYUdR9BZc0uziSoCkaCLccB+RDKgfA83V0EnzjtFydOpUWraMpdM5BgQcYQG5MycK+ux+ejJkFsqMQv71KwI4ESqECaZb6fUeq7K8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
