travis:
  secure:
    BINSTAR_TOKEN: QBRsIpl/jGf3kF5eVt55F0n9UcrjSw7RyvOSuzdoztXClU7h0E2hkdMHsUCKTWXL+cz5doUMdVykjq7e43mw1vNO/4EErK8WbAqQHh3xRMfx5A1XDPc5om+EsBv00oznzHr9SD85zpGhrRwVwReU2HuAYrF6Ww5cIRXkSjZGzqzuQd55aS6ItVyiYpLSZ4P6BSrGkA/tuYBexYvEswRcUPieC5kzklUzwml8zQ0mwLLMKZSjx2dwP2WkQzRuX5PQbsPZ3rJnMKp2FDk8ytNEWOUugoGMhNa9c2tZkLYahWs3Ev0PN4SqkfKO42oJkrX3dVjUQAZt/cVLQlLWEQNTGF+wPaJp2/WtbP9ibSrcE0UYjSh0QwDJz2UKB5lSTAi+n5nAf2/2QkQ0amTY2Pqnn8i4Zb3GH+OKuOOQtxuMWaNmr0TkMqurupNw/h6qHo1vyhJg7nuhD9cA7ZAwZZxAqYPpUVLYJbpDRKfYUR4Ye52o3XvimLcwslZokfnqP9+7BUfnSRzvNT06dhh1Gtv6YqJQsTIjPcN8Io/ji3ZdZ2Ohx8uGWZYnwYsTi2P8dQlYhDuInyoQfIWNKLsk7/X1HGcvFkb3HeWaPuWy4DAKR4C0lEemFkgZzQVjJ/KBwVyhkGChYZO9LMQyS7ToeIxkEHLeX1GsXzqYroNivKP1DAo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
