travis:
  secure:
    BINSTAR_TOKEN: v4J7DOE1mchNbseGbirjzm9R9Qdo5CQp5G+vqx+qx6G+mGgSVzFvw9c6BNwmGs66XWFu2fayIp+wyeaxunBMzBXbL1oyJwe1qOlT/v33NXKAe2f59k70XzAQ0ui5b4Ohv8c3jnraYpKLW8SnvYKwZtJ7Nbq0RP/ZUl5v4WXbtMs2xT+YEeI4aoM/vUcbzW8js9jGyeWuCv9RJ9suRc3hRJCIXRZj5UuVTEvyLHgs3xaTSUDKtBODNQJV5jHXP/B1b2EqCk3BDeeFkq62YgUDTqnooAluLDunNtYVI+fPPgY4NTOjavDB7wFlV38GpNUceW0UC19tsiXK6+zQYNMEHntGjDfE+p5u770+nc3EkYuIhwNgwjFizDIwyAW0pTb0ka6+TT9VtSw6dZdB6FIE1pk0UG4LQASmwSS8JTFwLDqH8QbEolYsFxfJGzrQyQiicNtA4044lsp7RJxtStctia9KQGtIuBLz6aYKgKQosJO/osA2IV6a7LN8Ma1WszXhgjm91zMP6NVhzZz3S+LjTq8omQa5RmOwBWOhtu6Qn8ktW2uRLRrYE4PftHDBueJwlQ2YoqlTU/Nx7UhSdVSy5Q0o4D+mtnKn0IcWnaCkQURh6jU62Ui+5v6VO64fhP0hX22y2wZz60TOkuOdBHjn7aQrwPQJ87/t8l7w49hm8eg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
